[versions]
guava = "33.4.6-jre"
junit = "5.12.1"
junit-platform = "1.12.1"
assertj = "3.27.3"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }


